### ISSUE TITLE
Create a landing page `config-webpack-plugin`

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/config-webpack-plugin#3]
## Current situation

We don't have any landing page to show off `config-webpack-plugin`. 😭 
## Requirements

While the `README` does a decent job, we would like to **enhance the user experience providing a simple landing page which transmit in a clear way how `config-webpack-plugin` works**.
### Details

No details for the creative one. 😉

**Comment by rmariuzzo** [comment]
@zxhadow is working on this: #1 – please talk to him before duplicating voluntary work (maybe via [our Gitter](https://gitter.im/rmariuzzo/config-webpack-plugin)).

**Comment by rafaelmedian** [comment]
@rmariuzzo 
My actual idea for the home page goes with a:
- header nav with github link, version, etc.
- gif explaining the process, both the terminal and the code editor overlaps while one of them is typing commands or writing code grabbing the user attentions. The same process should be explained in text.
- Markdown README rendered or not (this idea is an actual ripoff from here https://hyperterm.org/ which is awesome)

![screen shot 2016-08-12 at 7 41 36 pm](https://cloud.githubusercontent.com/assets/5257843/17639869/db396f1e-60c4-11e6-8f0d-5dd3ff14acc8.png)

**Comment by rmariuzzo** [comment]
Great! I love the concept you are proposing as well as the graphics! I'm not against using the markdown similar as hyperterm's website. I'm also willing to see the regular style without the markup (if possible).

**Comment by rafaelmedian** [comment]
Yeah, the markdown will do just fine, but I think there are different ones and we can try some of them online to see what could be better instead of trying to reproduce here.

Here are some markdown styles http://markedstyle.com/styles
